<a href="https://colab.research.google.com/github/scilove/ArewaDeepLearning/blob/main/Part_1_Deep_Learning_with_Pytorch/exercise_submissions/week_1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa Data Science Academy
### Deep Learning Cohort 2.0

#### Name: Muyiwa Obadara
#### Email: muyiwa.j.obadara@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

In [1]:
import torch

#### 2. Create a random tensor with shape (7, 7)

In [2]:
# Exercise 2 - Solution
t_rand = torch.rand(7, 7)
print(t_rand)

tensor([[0.4898, 0.3374, 0.3597, 0.2691, 0.1488, 0.0715, 0.0174],
        [0.2639, 0.4794, 0.4212, 0.0764, 0.2333, 0.3951, 0.3069],
        [0.7980, 0.4837, 0.0770, 0.0762, 0.1509, 0.8066, 0.6526],
        [0.6127, 0.5003, 0.2290, 0.3308, 0.7479, 0.0914, 0.9308],
        [0.2474, 0.9285, 0.8184, 0.6988, 0.6167, 0.9740, 0.9510],
        [0.2394, 0.5294, 0.7579, 0.9331, 0.4313, 0.5140, 0.2965],
        [0.2710, 0.5495, 0.2529, 0.5050, 0.0862, 0.4608, 0.1793]])


#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
t_rand2 = torch.rand(1, 7)

# Perform matrix multiplication
prod = torch.matmul(t_rand, t_rand2.T)
print(prod)

tensor([[0.4266],
        [0.5884],
        [0.5676],
        [0.6950],
        [1.3171],
        [0.9350],
        [0.5473]])


#### 4. Set the random seed to 0 and do 2 & 3 over again.

In [4]:
# Set the manual seed
torch.manual_seed(0)

# Create two random tensors
t_rand = torch.rand(7, 7)
t_rand2 = torch.rand(1, 7)

# Matrix multiply tensor
prod = torch.matmul(t_rand, t_rand2.T)
print(prod)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


#### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

- If there is, set the GPU random seed to 1234.

In [8]:
torch.cuda.manual_seed(1234)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to gpu

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create random tensor on gpu
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

t1 = t1.to('cuda')
t2 = t2.to('cuda')

print(t1)
print(t2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [12]:
prod = torch.matmul(t1, t2.T)
print(prod)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


#### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max = prod.max()
print(f"Max: {max}")

# Find min
min = prod.min()
print(f"Min: {min}")

Max: 0.5617256760597229
Min: 0.3647301495075226


#### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max

arg_max = prod.argmax()
print(f"Arg Max: {arg_max}")

# Find arg min
arg_min = prod.argmin()
print(f"Arg Min: {arg_min}")

Arg Max: 3
Arg Min: 0


#### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t = torch.rand(1, 1, 1, 10)

# Remove single dimensions
t_squeeze = t.squeeze()

# Print out tensors and their shapes
print("-"*30)
print(f"Tensor: {t}")
print(f"Tensor shape: {t.shape}")

print(f"Squeezed Tensor: {t_squeeze}")
print(f"Squeezed Tensor shape: {t_squeeze.shape}")

In [17]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t = torch.rand(1, 1, 1, 10)

# Remove single dimensions
t_squeeze = t.squeeze()

# Print out tensors and their shapes
print("-"*130)
print(f"Tensor: {t}")
print(f"Tensor shape: {t.shape}")
print("-"*130)
print(f"Squeezed Tensor: {t_squeeze}")
print(f"Squeezed Tensor shape: {t_squeeze.shape}")
print("-"*130)

----------------------------------------------------------------------------------------------------------------------------------
Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor shape: torch.Size([1, 1, 1, 10])
----------------------------------------------------------------------------------------------------------------------------------
Squeezed Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed Tensor shape: torch.Size([10])
----------------------------------------------------------------------------------------------------------------------------------
