<a href="https://colab.research.google.com/github/scilove/ArewaDeepLearning/blob/main/Part_1_Deep_Learning_with_Pytorch/exercise_submissions/week_1_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa Data Science Academy
### Deep Learning Cohort 2.0

#### Name: Muyiwa Obadara
#### Email: muyiwa.j.obadara@gmail.com
#### Title: Week 1 Solution

### Exercises Solution

In [1]:
import torch

#### 2. Create a random tensor with shape (7, 7)

In [5]:
# Exercise 2 - Solution
t_rand = torch.rand(7, 7)
print(t_rand)

tensor([[0.7481, 0.7659, 0.6517, 0.2453, 0.6564, 0.6033, 0.6838],
        [0.6910, 0.3596, 0.3533, 0.7965, 0.2192, 0.6559, 0.5773],
        [0.4921, 0.7606, 0.8995, 0.1012, 0.0277, 0.9436, 0.0327],
        [0.6026, 0.8919, 0.5979, 0.5715, 0.8086, 0.1390, 0.1390],
        [0.9355, 0.9688, 0.0398, 0.5500, 0.9524, 0.3935, 0.0555],
        [0.3787, 0.8589, 0.9380, 0.5898, 0.7836, 0.5803, 0.3994],
        [0.2597, 0.0177, 0.9133, 0.3021, 0.8289, 0.2538, 0.1557]])


#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
t_rand2 = torch.rand(1, 7)

# Perform matrix multiplication
prod = torch.matmul(t_rand, t_rand2.T)
print(prod)

tensor([[1.8234],
        [1.1525],
        [1.4293],
        [1.7035],
        [1.9708],
        [1.9026],
        [0.9738]])


#### 4. Set the random seed to 0 and do 2 & 3 over again.

In [8]:
# Set the manual seed
torch.manual_seed(0)

# Create two random tensors
t_rand = torch.rand(7, 7)
t_rand2 = torch.rand(1, 7)

# Matrix multiply tensor
prod = torch.matmul(t_rand, t_rand2.T)
print(prod)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


#### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

- If there is, set the GPU random seed to 1234.

In [9]:
torch.cuda.is_available()

False

### Additional Exercises Solution

**NOTE: NOT TO BE INCLUDED IN SUBMISSION FILE**\
HOW TO SUBMIT NOTES:
1. Clone the repository
```bash
git clone https://github.com/arewadataScience/ArewaDS-Deep-Learning.git
```
2. Save each week's notebooks in this subfolder `exercise_submissions`
3. Use the naming convension `week_{num}_solution.ipynb` e.g. `week_1_solution.ipynb`
4. Please, make sure all the clear runs without errors and keep cell outputs before submission.


SUBMIT ASSIGNMENT HERE: [CLICK ME ▶️](https://forms.gle/876vi4aNoFf4A2mU7)